import streamlit as st
from streamlit_drawable_canvas import st_canvas
from interactive_predict import AVAILABLE_MODELS, initRNNStateFromStrokes, load_model

CANVAS_WIDTH = 700
CANVAS_HEIGHT = 400

# State (equivalent to the "let" variables from JS)
ss = st.session_state
ss.setdefault("canvas_key", 0)                    # increase to get a fresh, empty canvas
ss.setdefault("temperature", 0.25)
ss.setdefault("all_raw_lines", [])                 # contains lines in form of lists of points: list([x, y]), !! not deltas
ss.setdefault("strokes", [])                       # contains all the strokes [dx, dy, p1, p2, p3]]
ss.setdefault("object_count", 0)                   # canvas objs already converted to strokes

ss.setdefault("x", 0)
ss.setdefault("y", 0)
ss.setdefault("dx", 0)
ss.setdefault("dy", 0)
ss.setdefault("model_state", None)
ss.setdefault("pen_state", [1, 0, 0]) # pen state [pen_down, pen_up, end]
ss.setdefault("prev_pen_state", [1, 0, 0]) # previous pen state [pen_down, pen_up, end]

# lines generated by the model
ss.setdefault("generated_lines", [])

# Update Functions
def restart():
    ss.canvas_key += 1 # new key results in a new empty canvas
    ss.all_raw_lines = []
    ss.strokes = []
    ss.object_count = 0
    ss.model_state = None
    print("helol")

# Layout (UI and DOM elements)
st.title("Pen Pal Canvas")
st.subheader("Interactive Sketch Prediction")
st.write("This demo attempts to finish the drawing of a cat, given whatever strokes you draw on the screen.")

col1, col2 = st.columns(2, vertical_alignment="bottom")

with col1:
    st.button("Clear", on_click=restart, use_container_width=True)
with col2:
    st.slider(
        "Temperature",
        min_value=0.0,
        max_value=1.0,
        step=0.05,
        key="temperature")

canvas_result = st_canvas(
    initial_drawing={"version": "4.4.0", "objects": ss.generated_lines},
    drawing_mode="freedraw",
    fill_color="rgba(255, 165, 0, 0.3)",  
    stroke_width=2,
    stroke_color="#FF0000", # JS says that the user always draws in red
    background_color="#EEEEEE",
    update_streamlit=True,
    width=CANVAS_WIDTH,
    height=CANVAS_HEIGHT,
    return_image_data=True,
    key=f"canvas{ss.canvas_key}",
)


# load model once when streamlit program starts:
if "model" not in ss:
    ss.model = load_model()


# equivalent to mouseDragged
# Note: Origin (0,0) sits in the top left corner
# Converts a fabric.js path (of the stroke) into the (x, y) format.
# Returns a list of (x, y) points
# streamlit returns a path of a line in an SVG path format,
# so these aren't exact mouse positions, but approximations
def get_points(path):
    points = []
    for c in path:
        if c[0] == 'M':                   # ["M", x, y] - Move to point
            points.append([c[1], c[2]])
        elif c[0] == 'Q':                 # ["Q", control_x, control_y, end_x, end_y], - Curve
            x, y = c[3], c[4]
            points.append([x, y])
        elif c[0] == 'L':                 # ["L", next_x, next_y]  - Line
            x, y = c[1], c[2]
            points.append([x, y])
    return points


# equivalent to mouseReleased
def on_new_line(raw_lines):
    if not len(raw_lines) > 0: # nothing drawn
        return

    model = ss.model

    raw_line_svg = raw_lines[-1] # newest stroke

    # path of the entire line user drew
    path = raw_line_svg["path"] # its [["M", x, y], ["Q", ...], ...], etc.

    # list of raw points converted from streamlit's SVG path
    # raw_line_points is equivalent to currentRawLine in mouseReleased from JS
    raw_line = get_points(path) # [[x, y], [x, y], ...]

    ss.all_raw_lines.append(raw_line)

    raw_line_simplified = model.simplify_line(raw_line)

    # the end point of previous line is needed
    # see p.mouseReleased in JS
    #   this will make the first displacement of this line very big
    #   which is useful information because model knows:
    #   the human ended this line here and then started a new line all the way here
    #   and that is somehow useful

    prev_line_end_point = (0, 0);
    if len(ss.all_raw_lines) > 1:
        prev_line_end_point = ss.all_raw_lines[-2][-1]

    stroke = model.line_to_stroke(raw_line_simplified, prev_line_end_point)
    strokes = ss.strokes + [stroke]

    initRNNStateFromStrokes(strokes)



def draw_line(x1, y1, x2, y2, color="#000000", width=2):
    print('drawing line')
    left, top = min(x1, x2), min(y1, y2)
    w, h = abs(x2 - x1), abs(y2 - y1)

    cx, cy = left + w / 2, top + h / 2

    # add object count so that this line isn't treated as a line
    # a user drew, so it wouldnt get converted to a stroke
    ss.object_count += 1
    ss.generated_lines.append({
        "type": "line",
        "originX": "left", "originY": "top",
        "left": left, "top": top,
        "width": w, "height": h,
        "x1": x1 - cx, "y1": y1 - cy,
        "x2": x2 - cx, "y2": y2 - cy,
        "stroke": color,
        "strokeWidth": width,
        "strokeLineCap": "round",
    })


# this is called whenever a new stroke was drawn
if canvas_result.json_data is not None:
    print("new line")

    objects = canvas_result.json_data.get("objects", [])
    if len(objects) > ss.object_count:                    # more strokes than previous drawing
        on_new_line(objects)
        ss.object_count = len(objects)                    # save # of objs seen






